### ISSUE TITLE
acmefetch-0.6.2 also won't build on debian9

### ISSUE THREAD

**Issue by udoL** [oetiker/AcmeFetch#21] opened 2017-08-31 18:27 UTC
Sorry, but an make with 0.6.2 fails on an plain debian9 too.

```
root@debian9-test:~/soft/acmefetch-0.6.2# make
Making all in thirdparty
make[1]: Verzeichnis „/root/soft/acmefetch-0.6.2/thirdparty“ wird betreten
  GEN      touch
Successfully installed Class-Accessor-0.34
Successfully installed Convert-ASN1-0.27
Successfully installed Crypt-Format-0.07
Successfully installed Crypt-RSA-Parse-0.043
Successfully installed Mozilla-CA-20160104
! Installing Net::SSLeay failed. See /root/soft/acmefetch-0.6.2/thirdparty/work/1504184979.6979/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Net::SSLeay' is not installed
! Bailing out the installation for IO-Socket-SSL-2.050.
Successfully installed Crypt-OpenSSL-Random-0.11
! Installing Crypt::OpenSSL::RSA failed. See /root/soft/acmefetch-0.6.2/thirdparty/work/1504184979.6979/build.log for details. Retry with --force to force install it.
Successfully installed Sub-Uplevel-0.2800
Successfully installed Test-Exception-0.43
Successfully installed JSON-2.94
Successfully installed Log-Any-1.049
Successfully installed Crypt-OpenSSL-Bignum-0.08
! Installing the dependencies failed: Module 'Net::SSLeay' is not installed, Module 'Crypt::OpenSSL::RSA' is not installed, Module 'IO::Socket::SSL' is not installed
! Bailing out the installation for Protocol-ACME-1.01.
Successfully installed Data-Processor-0.4.3
Successfully installed Pod-Usage-1.69 (upgraded from 1.68)
! Installing Crypt::OpenSSL::X509 failed. See /root/soft/acmefetch-0.6.2/thirdparty/work/1504184979.6979/build.log for details. Retry with --force to force install it.
13 distributions installed
Makefile:413: die Regel für Ziel „touch“ scheiterte
make[1]: *** [touch] Fehler 123
make[1]: Verzeichnis „/root/soft/acmefetch-0.6.2/thirdparty“ wird verlassen
Makefile:451: die Regel für Ziel „all-recursive“ scheiterte
make: *** [all-recursive] Fehler 1
```
touch PERL_MODULES and cpan update produce the same error - Net::SSLeay was not installed (and OpenSSL::RSA...).

**Comment by oetiker** [comment] 2017-09-01 07:17
have a look at the file /root/soft/acmefetch-0.6.2/thirdparty/work/1504184979.6979/build.log to see what the problem is ... maybe you don't have the openssl dev packages installed

**Comment by udoL** [comment] 2017-09-03 20:55
Hi,
libssl-dev is installed
```
dpkg -l | grep ssl
ii  libcrypt-openssl-bignum-perl  0.07-2                         amd64        Perl module to access OpenSSL multiprecision integer arithmetic libraries
ii  libcrypt-openssl-rsa-perl     0.28-5                         amd64        module for RSA encryption using OpenSSL
ii  libcrypt-openssl-x509-perl    1.8.7-3                        amd64        Perl extension to OpenSSL's X509 API
ii  libcrypt-ssleay-perl          0.73.04-2                      amd64        OpenSSL support for LWP
ii  libnet-ssleay-perl            1.80-1                         amd64        Perl module for Secure Sockets Layer (SSL)
ii  libssl-dev:amd64              1.1.0f-3                       amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                    1.1.0f-3                       all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.2:amd64             1.0.2l-2                       amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64               1.1.0f-3                       amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                       1.1.0f-3                       amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  perl-openssl-defaults:amd64   3                              amd64        version compatibility baseline for Perl OpenSSL packages
```
 and some ssl-things are build without trouble (SSLeay not):
```
Successfully installed Crypt-RSA-Parse-0.043
! Installing Net::SSLeay failed. See /home/u/soft/acmefetch-0.6.2/thirdparty/work/1504470928.12479/build.log for details. Retry with --force to force install it.
Successfully installed Crypt-OpenSSL-Bignum-0.08
Successfully installed Crypt-OpenSSL-Random-0.11
! Installing Crypt::OpenSSL::RSA failed. See /home/u/soft/acmefetch-0.6.2/thirdparty/work/1504470928.12479/build.log for details. Retry with --force to force install it.
```
But in the logfiles are such errors like this:
```
x86_64-linux-gnu-gcc -c  -I/usr/include -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BIT
S=64 -O2 -g   -DVERSION=\"1.81\" -DXS_VERSION=\"1.81\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"   SSLeay.c
SSLeay.xs: In function ‘ssleay_session_secret_cb_invoke’:
SSLeay.xs:834:25: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         SSL_CIPHER *c = sk_SSL_CIPHER_value(peer_ciphers,i);
                         ^~~~~~~~~~~~~~~~~~~
SSLeay.xs:854:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
             *cipher = sk_SSL_CIPHER_value(peer_ciphers, SvIV(pref_cipher));
                     ^
SSLeay.xs: In function ‘XS_Net__SSLeay_CTX_tlsv1_new’:
SSLeay.xs:1583:6: warning: ‘TLSv1_method’ is deprecated [-Wdeprecated-declarations]
      RETVAL = SSL_CTX_new (TLSv1_method());
      ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from SSLeay.xs:167:
/usr/include/openssl/ssl.h:1612:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
SSLeay.xs: In function ‘XS_Net__SSLeay_CTX_tlsv1_1_new’:
SSLeay.xs:1592:6: warning: ‘TLSv1_1_method’ is deprecated [-Wdeprecated-declarations]
      RETVAL = SSL_CTX_new (TLSv1_1_method());
      ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from SSLeay.xs:167:
/usr/include/openssl/ssl.h:1618:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
 ^
SSLeay.xs: In function ‘XS_Net__SSLeay_CTX_tlsv1_2_new’:
SSLeay.xs:1603:6: warning: ‘TLSv1_2_method’ is deprecated [-Wdeprecated-declarations]
      RETVAL = SSL_CTX_new (TLSv1_2_method());
      ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from SSLeay.xs:167:
/usr/include/openssl/ssl.h:1624:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
 ^
SSLeay.c: In function ‘XS_Net__SSLeay_BIO_f_ssl’:
SSLeay.c:4251:9: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  RETVAL = BIO_f_ssl();
...
```
And in the log is also "cc1: all warnings being treated as errors"...

Hmm, with openssl 1.1.0f-4 remove debian tls1.0 + tls1.1 but there is still 1.1.0f-3 installed.

**Comment by oetiker** [comment] 2017-09-04 07:01
it seems there is a problem with building that perl module on your debian instance ...

**Comment by udoL** [comment] 2017-09-07 07:54
Hi,
yes but it seems that is acme-fetch related?!

Because Crypt::OpenSSL::X509 work with cpan:
```
cpan[1]> install Crypt::OpenSSL::X509
Crypt::OpenSSL::X509 is up to date (1.807).
```
But not with the make from acmefetch:
`! Installing Crypt::OpenSSL::X509 failed. See /home/u/soft/acmefetch-0.6.2/thirdparty/work/1504769911.22066/build.log for details. Retry with --force to force install it.`

But I'm one step further. cpan gives an hint why Net::SSLeay isn't installable:
```
cpan[2]> install Net::SSLeay
Running install for module 'Net::SSLeay'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.81.tar.gz
...
In file included from /usr/include/openssl/objects.h:916:0,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from SSLeay.xs:167:
/usr/include/openssl/ocsp.h:336:1: note: expected ‘OCSP_CERTID * {aka struct ocsp_cert_id_st *}’ but argument is of type ‘const OCSP_CERTID * {aka const struct ocsp_cert_id_st *}’
 DECLARE_ASN1_FUNCTIONS(OCSP_CERTID)
 ^
rm -f blib/arch/auto/Net/SSLeay/SSLeay.so
LD_RUN_PATH="/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu" x86_64-linux-gnu-gcc  -shared -L/usr -L/usr/lib -L/usr/local/lib -fstack-protector-strong  SSLeay.o  -o blib/arch/auto/Net/SSLeay/SSLeay.so  \
   -L/usr -L/usr/lib -lssl -lcrypto -lz   \
  
/usr/bin/ld: cannot find -lz
```
After installing zlib stuff I stuck with Crypt::OpenSSL::X509 only.
`apt install zlib1g-dev libzstd-dev`
content of acmefetch-0.6.2/thirdparty/work/1504770166.22597/build.log:
```
cpanm (App::cpanminus) 1.7043 on perl 5.024001 built for x86_64-linux-gnu-thread-multi
Work directory is /home/u/soft/acmefetch-0.6.2/thirdparty/work/1504770166.22597
You have make /usr/bin/make
You have /usr/bin/wget
You have /bin/tar: tar (GNU tar) 1.29
Copyright © 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL Version 3 oder später <http://gnu.org/licenses/gpl.html>
Dies ist freie Software: Sie dürfen sie ändern und weiter verbreiten.
Es gibt KEINERLEI GARANTIE, so weit das Gesetz es erlaubt.

Geschrieben von John Gilmore und Jay Fenlason.
You have /usr/bin/unzip
Searching Crypt::RSA::Parse (== 0.043) on cpanmetadb ...
Crypt::RSA::Parse is up to date. (0.043)
Searching Protocol::ACME (== 1.01) on cpanmetadb ...
Protocol::ACME is up to date. (1.01)
Searching Data::Processor () on cpanmetadb ...
Data::Processor is up to date. (0.4.3)
Searching Pod::Usage () on cpanmetadb ...
Pod::Usage is up to date. (1.69)
Searching JSON () on cpanmetadb ...
JSON is up to date. (2.94)
Searching Crypt::OpenSSL::X509 () on cpanmetadb ...
--> Working on Crypt::OpenSSL::X509
Fetching http://www.cpan.org/authors/id/D/DA/DANIEL/Crypt-OpenSSL-X509-1.807.tar.gz
-> OK
Unpacking Crypt-OpenSSL-X509-1.807.tar.gz
Copying Crypt-OpenSSL-X509-1.807.tar.gz to /home/u/soft/acmefetch-0.6.2/thirdparty/CPAN/authors/id/D/DA/DANIEL/Crypt-OpenSSL-X509-1.807.tar.gz
Entering Crypt-OpenSSL-X509-1.807
Checking configure dependencies from META.yml
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.10_02)
Configuring Crypt-OpenSSL-X509-1.804
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Crypt::OpenSSL::X509
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.10_02)
Building Crypt-OpenSSL-X509-1.804
make[2]: Verzeichnis „/home/u/soft/acmefetch-0.6.2/thirdparty/work/1504770166.22597/Crypt-OpenSSL-X509-1.807“ wird betreten
cp X509.pm blib/lib/Crypt/OpenSSL/X509.pm
Running Mkbootstrap for X509 ()
chmod 644 "X509.bs"
"/usr/bin/perl" "-Iinc" -MExtUtils::Command::MM -e 'cp_nonempty' -- X509.bs blib/arch/auto/Crypt/OpenSSL/X509/X509.bs 644
"/usr/bin/perl" "-Iinc" "/usr/local/share/perl/5.24.1/ExtUtils/xsubpp"  -typemap '/usr/share/perl/5.24/ExtUtils/typemap' -typemap '/home/u/soft/acmefetch-0.6.2/thirdparty/work/1504770166.22597/Crypt-OpenSSL-X509-1.807/typemap'  X509.xs > X509.xsc
mv X509.xsc X509.c
x86_64-linux-gnu-gcc -c  -I/usr/include/openssl -I/usr/local/include/ssl -I/usr/local/ssl/include -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -Wall -Werror   -DVERSION=\"1.807\" -DXS_VERSION=\"1.807\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.24/CORE"   X509.c
X509.xs: In function ‘_decode_netscape’:
X509.xs:217:5: error: unknown type name ‘NETSCAPE_X509’
     NETSCAPE_X509 nx;
     ^~~~~~~~~~~~~
X509.xs:222:7: error: request for member ‘header’ in something not a structure or union
     nx.header = &os;
       ^
X509.xs:223:7: error: request for member ‘cert’ in something not a structure or union
     nx.cert   = x509;
       ^
In file included from X509.xs:5:0:
X509.xs:225:38: error: ‘NETSCAPE_X509_it’ undeclared (first use in this function)
     ASN1_item_i2d_bio(ASN1_ITEM_rptr(NETSCAPE_X509), bio, &nx);
                                      ^
X509.xs:225:38: note: each undeclared identifier is reported only once for each function it appears in
X509.xs: In function ‘XS_Crypt__OpenSSL__X509___X509_cleanup’:
X509.xs:357:3: error: ‘ERR_remove_state’ is deprecated [-Werror=deprecated-declarations]
   ERR_remove_state(0);
   ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from X509.xs:5:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
X509.xs: In function ‘XS_Crypt__OpenSSL__X509_accessor’:
X509.xs:401:31: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
     i2a_ASN1_INTEGER(bio, x509->cert_info->serialNumber);
                               ^~
X509.xs:420:43: error: passing argument 1 of ‘OPENSSL_sk_num’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     for (j = 0; j < sk_OPENSSL_STRING_num(emlst); j++) {
                                           ^~~~~
In file included from /usr/include/openssl/crypto.h:28:0,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/asn1.h:16,
                 from X509.xs:5:
/usr/include/openssl/stack.h:23:5: note: expected ‘const OPENSSL_STACK * {aka const struct stack_st *}’ but argument is of type ‘struct stack_st_OPENSSL_STRING *’
 int OPENSSL_sk_num(const OPENSSL_STACK *);
     ^~~~~~~~~~~~~~
X509.xs:421:53: error: passing argument 1 of ‘OPENSSL_sk_value’ from incompatible pointer type [-Werror=incompatible-pointer-types]
       BIO_printf(bio, "%s", sk_OPENSSL_STRING_value(emlst, j));
                                                     ^~~~~
In file included from /usr/include/openssl/crypto.h:28:0,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/asn1.h:16,
                 from X509.xs:5:
/usr/include/openssl/stack.h:24:7: note: expected ‘const OPENSSL_STACK * {aka const struct stack_st *}’ but argument is of type ‘struct stack_st_OPENSSL_STRING *’
 void *OPENSSL_sk_value(const OPENSSL_STACK *, int);
       ^~~~~~~~~~~~~~~~
X509.xs:421:25: error: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘void *’ [-Werror=format=]
       BIO_printf(bio, "%s", sk_OPENSSL_STRING_value(emlst, j));
                         ^
X509.xs: In function ‘XS_Crypt__OpenSSL__X509_bit_length’:
X509.xs:531:14: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
   switch(pkey->type) {
              ^~
X509.xs: In function ‘XS_Crypt__OpenSSL__X509_CRL_CRL_accessor’:
X509.xs:1482:29: error: dereferencing pointer to incomplete type ‘X509_CRL {aka struct X509_crl_st}’
     i2a_ASN1_OBJECT(bio, crl->sig_alg->algorithm);
                             ^~
cc1: all warnings being treated as errors
Makefile:344: die Regel für Ziel „X509.o“ scheiterte
make[2]: *** [X509.o] Fehler 1
make[2]: Verzeichnis „/home/u/soft/acmefetch-0.6.2/thirdparty/work/1504770166.22597/Crypt-OpenSSL-X509-1.807“ wird verlassen
-> FAIL Installing Crypt::OpenSSL::X509 failed. See /home/u/soft/acmefetch-0.6.2/thirdparty/work/1504770166.22597/build.log for details. Retry with --force to force install it.
Searching Net::SSLeay () on cpanmetadb ...
Net::SSLeay is up to date. (1.81)
Searching IO::Socket::SSL () on cpanmetadb ...
IO::Socket::SSL is up to date. (2.051)
Searching Mozilla::CA () on cpanmetadb ...
Mozilla::CA is up to date. (20160104)
```

**Comment by oetiker** [comment] 2017-09-07 09:55
acmefetch tries to build any module missing from your perl setup ... in that sense, yes ... try 'touch PERL_MODULES' to make sure you get the latest updates ...

**Comment by udoL** [comment] 2017-09-08 18:24
Hi,
touch PERL_MODULES don't help...

**Comment by maettu** [comment] 2017-09-09 08:21
Crypt::OpenSSL::X509 does not install on debian 9 for me either. (Not digging into this for a long time, though.)
I wonder if it was feasible to use the distro packages and have the installer not insist on local dependencies for those modules if they are globally installed.
Hackishly, one is tempted to apt-get install the various libcrypt- modules and remove the respective lines from PERL_MODULES.

**Comment by oetiker** [comment] 2017-09-09 09:22
yes you CAN use the distro package ... no problem

Tobias Oetiker
tobi@oetiker.ch
062 775 9902

**Comment by oetiker** [comment] 2017-09-09 09:27
acmefetsch does NOT install modules which are already present locally 

Tobias Oetiker
tobi@oetiker.ch
062 775 9902

**Comment by udoL** [comment] 2017-09-09 09:54
> acmefetsch does NOT install modules which are already present locally

Ähh, no - don't work for me.
libcrypt-openssl-x509-perl is installed:
```
# dpkg -L libcrypt-openssl-x509-perl
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/perl5
/usr/lib/x86_64-linux-gnu/perl5/5.24
/usr/lib/x86_64-linux-gnu/perl5/5.24/Crypt
/usr/lib/x86_64-linux-gnu/perl5/5.24/Crypt/OpenSSL
/usr/lib/x86_64-linux-gnu/perl5/5.24/Crypt/OpenSSL/X509.pm
/usr/lib/x86_64-linux-gnu/perl5/5.24/auto
/usr/lib/x86_64-linux-gnu/perl5/5.24/auto/Crypt
/usr/lib/x86_64-linux-gnu/perl5/5.24/auto/Crypt/OpenSSL
/usr/lib/x86_64-linux-gnu/perl5/5.24/auto/Crypt/OpenSSL/X509
/usr/lib/x86_64-linux-gnu/perl5/5.24/auto/Crypt/OpenSSL/X509/X509.so
/usr/share
/usr/share/doc
/usr/share/doc/libcrypt-openssl-x509-perl
/usr/share/doc/libcrypt-openssl-x509-perl/NEWS.Debian.gz
/usr/share/doc/libcrypt-openssl-x509-perl/TODO
/usr/share/doc/libcrypt-openssl-x509-perl/changelog.Debian.gz
/usr/share/doc/libcrypt-openssl-x509-perl/changelog.gz
/usr/share/doc/libcrypt-openssl-x509-perl/copyright
/usr/share/man
/usr/share/man/man3
/usr/share/man/man3/Crypt::OpenSSL::X509.3pm.gz

ls -lsa /usr/lib/x86_64-linux-gnu/perl5/5.24/Crypt/OpenSSL/X509.pm
12 -rw-r--r-- 1 root root 9392 Jan  3  2017 /usr/lib/x86_64-linux-gnu/perl5/5.24/Crypt/OpenSSL/X509.pm
```
But make tried to install Crypt::OpenSSL::X509 again:
`! Installing Crypt::OpenSSL::X509 failed. See /home/u/soft/acmefetch-0.6.2/thirdparty/work/1504950557.25091/build.log for details. Retry with --force to force install it.`

But with removing of Crypt::OpenSSL::X509 from PERL_MODULES it's work!

**Comment by oetiker** [comment] 2017-09-09 10:20
if the installed version is older than the version provided
in the acmefetch package than the verion from acmefetch will be installed.

Tobias Oetiker
tobi@oetiker.ch
062 775 9902

**Comment by udoL** [comment] 2017-09-14 19:54
acmefetch was builded with the stretch version of Crypt::OpenSSL::X509.

To run the program I must change one line:
```
73c73
<                         `$bin version 2>&1` =~ /^OpenSSL 1.1.0/ or return "Openssl $bin not found";
---
>                         `$bin version 2>&1` =~ /^OpenSSL 1.0/ or return "Openssl $bin not found";
```
Because of an newer version in debian stretch: "OpenSSL 1.1.0f  25 May 2017"

**Comment by udoL** [comment] 2017-09-17 18:00
acmefetch was builded with the stretch version of Crypt::OpenSSL::X509.

To run the program I must change one line:
```
73c73
<                         `$bin version 2>&1` =~ /^OpenSSL 1.1.0/ or return "Openssl $bin not found";
---
>                         `$bin version 2>&1` =~ /^OpenSSL 1.0/ or return "Openssl $bin not found";
```
Because of an newer version in debian stretch: "OpenSSL 1.1.0f  25 May 2017"

**Closed as completed** 2020-09-17 13:37 UTC
